# Generated by Django 3.2.9 on 2022-09-11 15:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('p_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('p_name', models.TextField()),
                ('p_address_1', models.TextField(blank=True)),
                ('p_address_2', models.TextField(blank=True)),
                ('p_author', models.CharField(default='System', max_length=100)),
                ('p_date', models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 27, 21, 843052, tzinfo=utc))),
                ('p_id_rccm', models.CharField(blank=True, max_length=100)),
                ('p_id_id', models.CharField(blank=True, max_length=100)),
                ('p_id_tva', models.CharField(blank=True, max_length=100)),
                ('p_id_nif', models.CharField(blank=True, max_length=100)),
                ('p_cp_1_name', models.CharField(blank=True, max_length=100)),
                ('p_cp_1_phone', models.CharField(blank=True, max_length=100)),
                ('p_cp_1_email', models.CharField(blank=True, max_length=100)),
                ('p_cp_2_name', models.CharField(blank=True, max_length=100)),
                ('p_cp_2_phone', models.CharField(blank=True, max_length=100)),
                ('p_cp_2_email', models.CharField(blank=True, max_length=100)),
                ('p_contacts_email', models.CharField(blank=True, max_length=100)),
                ('p_contacts_phone', models.CharField(blank=True, max_length=100)),
                ('p_contacts_fax', models.CharField(blank=True, max_length=100)),
                ('p_contacts_website', models.CharField(blank=True, max_length=100)),
                ('p_is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
