# Generated by Django 3.1.13 on 2022-07-18 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.TextField()),
                ('p_address', models.TextField()),
                ('p_author', models.TextField()),
                ('p_email', models.TextField()),
                ('p_date', models.DateTimeField(default=datetime.datetime(2022, 7, 18, 9, 40, 38, 994760))),
                ('l_company', models.TextField()),
            ],
        ),
    ]
