# Generated by Django 3.1.13 on 2022-07-18 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_auto_20220718_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='l_company',
            new_name='p_company',
        ),
        migrations.AddField(
            model_name='party',
            name='p_is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 9, 46, 24, 165711)),
        ),
    ]
