# Generated by Django 3.2.9 on 2022-09-11 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_party_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 28, 0, 244452, tzinfo=utc)),
        ),
    ]
