# Generated by Django 3.1.13 on 2022-07-18 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_auto_20220718_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 10, 25, 11, 905351)),
        ),
    ]
