# Generated by Django 3.1.13 on 2022-07-18 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0006_auto_20220718_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 10, 43, 8, 395045)),
        ),
    ]
