# Generated by Django 3.1.13 on 2022-07-18 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0007_auto_20220718_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 11, 13, 38, 141885)),
        ),
        migrations.AlterField(
            model_name='party',
            name='p_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
