# Generated by Django 3.1.13 on 2022-07-20 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0008_auto_20220718_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 20, 10, 9, 37, 610296)),
        ),
    ]
