# Generated by Django 3.1.13 on 2022-07-21 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0009_auto_20220720_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 21, 2, 37, 21, 425268)),
        ),
    ]
