# Generated by Django 4.0.6 on 2022-07-23 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0010_auto_20220721_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='p_address',
            new_name='p_address_1',
        ),
        migrations.RemoveField(
            model_name='party',
            name='p_company',
        ),
        migrations.RemoveField(
            model_name='party',
            name='p_email',
        ),
        migrations.AddField(
            model_name='party',
            name='p_address_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='party',
            name='p_cp_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='p_cp_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='p_id',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 14, 50, 5, 490143)),
        ),
    ]
