# Generated by Django 4.0.6 on 2022-07-23 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0012_alter_party_p_address_1_alter_party_p_address_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='p_author',
            field=models.TextField(default='System'),
        ),
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 15, 20, 40, 128686)),
        ),
    ]
