# Generated by Django 4.0.6 on 2022-07-24 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0013_alter_party_p_author_alter_party_p_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='p_contacts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='p_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 2, 25, 56, 529275)),
        ),
    ]
