# Generated by Django 3.2.9 on 2022-09-11 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0003_alter_party_p_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('po_no', models.AutoField(primary_key=True, serialize=False)),
                ('po_date', models.DateField()),
                ('po_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.party')),
            ],
        ),
    ]
