# Generated by Django 3.1.13 on 2022-07-18 10:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('p_uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('p_date', models.DateTimeField()),
                ('p_followup', models.DateTimeField()),
                ('p_part_no', models.TextField()),
                ('p_description', models.TextField()),
                ('p_quote_ref', models.TextField()),
                ('p_comments', models.TextField()),
                ('p_received', models.BooleanField(default=False)),
                ('p_discount', models.IntegerField()),
                ('p_quantity', models.IntegerField()),
                ('p_base_price', models.IntegerField()),
                ('po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PO.po')),
            ],
        ),
    ]
