# Generated by Django 3.1.13 on 2022-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PO', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_base_price',
            field=models.FloatField(),
        ),
    ]
